// Copyright (c) 2026 OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: plugin/pb/kms/plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// See kms.Open and kms.OpenOptions.
type OpenRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowEnvironment bool                   `protobuf:"varint,1,opt,name=allow_environment,json=allowEnvironment,proto3" json:"allow_environment,omitempty"`
	ConfigMap        *structpb.Struct       `protobuf:"bytes,10,opt,name=config_map,json=configMap,proto3" json:"config_map,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetAllowEnvironment() bool {
	if x != nil {
		return x.AllowEnvironment
	}
	return false
}

func (x *OpenRequest) GetConfigMap() *structpb.Struct {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KmsId         string                 `protobuf:"bytes,1,opt,name=kms_id,json=kmsId,proto3" json:"kms_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetKmsId() string {
	if x != nil {
		return x.KmsId
	}
	return ""
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KmsId         string                 `protobuf:"bytes,1,opt,name=kms_id,json=kmsId,proto3" json:"kms_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *CloseRequest) GetKmsId() string {
	if x != nil {
		return x.KmsId
	}
	return ""
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{3}
}

// See kms.KMS.GetKey and kms.KeyOptions.
type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KmsId         string                 `protobuf:"bytes,1,opt,name=kms_id,json=kmsId,proto3" json:"kms_id,omitempty"`
	ConfigMap     *structpb.Struct       `protobuf:"bytes,10,opt,name=config_map,json=configMap,proto3" json:"config_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *GetKeyRequest) GetKmsId() string {
	if x != nil {
		return x.KmsId
	}
	return ""
}

func (x *GetKeyRequest) GetConfigMap() *structpb.Struct {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *GetKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type CloseKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseKeyRequest) Reset() {
	*x = CloseKeyRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseKeyRequest) ProtoMessage() {}

func (x *CloseKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseKeyRequest.ProtoReflect.Descriptor instead.
func (*CloseKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CloseKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type CloseKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseKeyResponse) Reset() {
	*x = CloseKeyResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseKeyResponse) ProtoMessage() {}

func (x *CloseKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseKeyResponse.ProtoReflect.Descriptor instead.
func (*CloseKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{7}
}

// See kms.Key.Encrypt and kms.CipherOptions.
type EncryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	Aad           []byte                 `protobuf:"bytes,11,opt,name=aad,proto3" json:"aad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *EncryptRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *EncryptRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncryptRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

type EncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *EncryptResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// See kms.Key.Decrypt and kms.CipherOptions.
type DecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	Aad           []byte                 `protobuf:"bytes,11,opt,name=aad,proto3" json:"aad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *DecryptRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *DecryptRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DecryptRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *DecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

// See kms.Key.Sign and kms.SignOptions.
type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	Prehashed     bool                   `protobuf:"varint,11,opt,name=prehashed,proto3" json:"prehashed,omitempty"`
	Hash          int32                  `protobuf:"varint,12,opt,name=hash,proto3" json:"hash,omitempty"` // The value of HashFunc().
	Opts          *SignerOpts            `protobuf:"bytes,13,opt,name=opts,proto3,oneof" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *SignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignRequest) GetPrehashed() bool {
	if x != nil {
		return x.Prehashed
	}
	return false
}

func (x *SignRequest) GetHash() int32 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *SignRequest) GetOpts() *SignerOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// See kms.Key.Verify and kms.VerifyOptions.
type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	Prehashed     bool                   `protobuf:"varint,11,opt,name=prehashed,proto3" json:"prehashed,omitempty"`
	Hash          int32                  `protobuf:"varint,12,opt,name=hash,proto3" json:"hash,omitempty"` // The value of HashFunc().
	Opts          *SignerOpts            `protobuf:"bytes,13,opt,name=opts,proto3,oneof" json:"opts,omitempty"`
	Signature     []byte                 `protobuf:"bytes,14,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *VerifyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VerifyRequest) GetPrehashed() bool {
	if x != nil {
		return x.Prehashed
	}
	return false
}

func (x *VerifyRequest) GetHash() int32 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *VerifyRequest) GetOpts() *SignerOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

func (x *VerifyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{15}
}

type ExportPublicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPublicRequest) Reset() {
	*x = ExportPublicRequest{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPublicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPublicRequest) ProtoMessage() {}

func (x *ExportPublicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPublicRequest.ProtoReflect.Descriptor instead.
func (*ExportPublicRequest) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ExportPublicRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type ExportPublicResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This might need to support different encodings in the future - for now,
	// all of *rsa.PublicKey, *ecdsa.PublicKey and ed25519.PublicKey are easily
	// transferred in PKIX ASN.1 DER encoding via x509.MarshalPKIXPublicKey and
	// x509.ParsePKIXPublicKey.
	//
	// Once additional encodings are needed, use the `oneof` keyword to expose
	// those as separate fields.
	PkixAsn1Der   []byte `protobuf:"bytes,1,opt,name=pkix_asn1_der,json=pkixAsn1Der,proto3" json:"pkix_asn1_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPublicResponse) Reset() {
	*x = ExportPublicResponse{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPublicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPublicResponse) ProtoMessage() {}

func (x *ExportPublicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPublicResponse.ProtoReflect.Descriptor instead.
func (*ExportPublicResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ExportPublicResponse) GetPkixAsn1Der() []byte {
	if x != nil {
		return x.PkixAsn1Der
	}
	return nil
}

// This represents the well-known subset of crypto.SignerOpts. Note that
// HashFunc() is already embedded in SignRequest/VerifyRequest, this way the
// SignerOpts fields themselves can be `optional`.
type SignerOpts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*SignerOpts_Pss
	//	*SignerOpts_Ed25519
	Type          isSignerOpts_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignerOpts) Reset() {
	*x = SignerOpts{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerOpts) ProtoMessage() {}

func (x *SignerOpts) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerOpts.ProtoReflect.Descriptor instead.
func (*SignerOpts) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *SignerOpts) GetType() isSignerOpts_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SignerOpts) GetPss() *SignerOptsPSS {
	if x != nil {
		if x, ok := x.Type.(*SignerOpts_Pss); ok {
			return x.Pss
		}
	}
	return nil
}

func (x *SignerOpts) GetEd25519() *SignerOptsEd25519 {
	if x != nil {
		if x, ok := x.Type.(*SignerOpts_Ed25519); ok {
			return x.Ed25519
		}
	}
	return nil
}

type isSignerOpts_Type interface {
	isSignerOpts_Type()
}

type SignerOpts_Pss struct {
	Pss *SignerOptsPSS `protobuf:"bytes,1,opt,name=pss,proto3,oneof"`
}

type SignerOpts_Ed25519 struct {
	Ed25519 *SignerOptsEd25519 `protobuf:"bytes,2,opt,name=ed25519,proto3,oneof"` // crypto/ecdsa defines no options.
}

func (*SignerOpts_Pss) isSignerOpts_Type() {}

func (*SignerOpts_Ed25519) isSignerOpts_Type() {}

// See crypto/rsa.PSSOptions.
type SignerOptsPSS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaltLength    int32                  `protobuf:"varint,1,opt,name=salt_length,json=saltLength,proto3" json:"salt_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignerOptsPSS) Reset() {
	*x = SignerOptsPSS{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerOptsPSS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerOptsPSS) ProtoMessage() {}

func (x *SignerOptsPSS) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerOptsPSS.ProtoReflect.Descriptor instead.
func (*SignerOptsPSS) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *SignerOptsPSS) GetSaltLength() int32 {
	if x != nil {
		return x.SaltLength
	}
	return 0
}

// See crypto/ed25519.Options.
type SignerOptsEd25519 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignerOptsEd25519) Reset() {
	*x = SignerOptsEd25519{}
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerOptsEd25519) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerOptsEd25519) ProtoMessage() {}

func (x *SignerOptsEd25519) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_kms_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerOptsEd25519.ProtoReflect.Descriptor instead.
func (*SignerOptsEd25519) Descriptor() ([]byte, []int) {
	return file_plugin_pb_kms_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *SignerOptsEd25519) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

var File_plugin_pb_kms_plugin_proto protoreflect.FileDescriptor

const file_plugin_pb_kms_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1aplugin/pb/kms/plugin.proto\x12\x03kms\x1a\x1cgoogle/protobuf/struct.proto\"r\n" +
	"\vOpenRequest\x12+\n" +
	"\x11allow_environment\x18\x01 \x01(\bR\x10allowEnvironment\x126\n" +
	"\n" +
	"config_map\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\tconfigMap\"%\n" +
	"\fOpenResponse\x12\x15\n" +
	"\x06kms_id\x18\x01 \x01(\tR\x05kmsId\"%\n" +
	"\fCloseRequest\x12\x15\n" +
	"\x06kms_id\x18\x01 \x01(\tR\x05kmsId\"\x0f\n" +
	"\rCloseResponse\"^\n" +
	"\rGetKeyRequest\x12\x15\n" +
	"\x06kms_id\x18\x01 \x01(\tR\x05kmsId\x126\n" +
	"\n" +
	"config_map\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\tconfigMap\"'\n" +
	"\x0eGetKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"(\n" +
	"\x0fCloseKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"\x12\n" +
	"\x10CloseKeyResponse\"M\n" +
	"\x0eEncryptRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04data\x18\n" +
	" \x01(\fR\x04data\x12\x10\n" +
	"\x03aad\x18\v \x01(\fR\x03aad\"1\n" +
	"\x0fEncryptResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\"M\n" +
	"\x0eDecryptRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04data\x18\n" +
	" \x01(\fR\x04data\x12\x10\n" +
	"\x03aad\x18\v \x01(\fR\x03aad\"/\n" +
	"\x0fDecryptResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\"\x9d\x01\n" +
	"\vSignRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04data\x18\n" +
	" \x01(\fR\x04data\x12\x1c\n" +
	"\tprehashed\x18\v \x01(\bR\tprehashed\x12\x12\n" +
	"\x04hash\x18\f \x01(\x05R\x04hash\x12(\n" +
	"\x04opts\x18\r \x01(\v2\x0f.kms.SignerOptsH\x00R\x04opts\x88\x01\x01B\a\n" +
	"\x05_opts\",\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"\xbd\x01\n" +
	"\rVerifyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04data\x18\n" +
	" \x01(\fR\x04data\x12\x1c\n" +
	"\tprehashed\x18\v \x01(\bR\tprehashed\x12\x12\n" +
	"\x04hash\x18\f \x01(\x05R\x04hash\x12(\n" +
	"\x04opts\x18\r \x01(\v2\x0f.kms.SignerOptsH\x00R\x04opts\x88\x01\x01\x12\x1c\n" +
	"\tsignature\x18\x0e \x01(\fR\tsignatureB\a\n" +
	"\x05_opts\"\x10\n" +
	"\x0eVerifyResponse\",\n" +
	"\x13ExportPublicRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\":\n" +
	"\x14ExportPublicResponse\x12\"\n" +
	"\rpkix_asn1_der\x18\x01 \x01(\fR\vpkixAsn1Der\"p\n" +
	"\n" +
	"SignerOpts\x12&\n" +
	"\x03pss\x18\x01 \x01(\v2\x12.kms.SignerOptsPSSH\x00R\x03pss\x122\n" +
	"\aed25519\x18\x02 \x01(\v2\x16.kms.SignerOptsEd25519H\x00R\aed25519B\x06\n" +
	"\x04type\"0\n" +
	"\rSignerOptsPSS\x12\x1f\n" +
	"\vsalt_length\x18\x01 \x01(\x05R\n" +
	"saltLength\"-\n" +
	"\x11SignerOptsEd25519\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext2\xdf\x03\n" +
	"\x03KMS\x12+\n" +
	"\x04Open\x12\x10.kms.OpenRequest\x1a\x11.kms.OpenResponse\x12.\n" +
	"\x05Close\x12\x11.kms.CloseRequest\x1a\x12.kms.CloseResponse\x121\n" +
	"\x06GetKey\x12\x12.kms.GetKeyRequest\x1a\x13.kms.GetKeyResponse\x127\n" +
	"\bCloseKey\x12\x14.kms.CloseKeyRequest\x1a\x15.kms.CloseKeyResponse\x124\n" +
	"\aEncrypt\x12\x13.kms.EncryptRequest\x1a\x14.kms.EncryptResponse\x124\n" +
	"\aDecrypt\x12\x13.kms.DecryptRequest\x1a\x14.kms.DecryptResponse\x12+\n" +
	"\x04Sign\x12\x10.kms.SignRequest\x1a\x11.kms.SignResponse\x121\n" +
	"\x06Verify\x12\x12.kms.VerifyRequest\x1a\x13.kms.VerifyResponse\x12C\n" +
	"\fExportPublic\x12\x18.kms.ExportPublicRequest\x1a\x19.kms.ExportPublicResponseB8Z6github.com/openbao/go-kms-wrapping/plugin/v2/pb/kms;pbb\x06proto3"

var (
	file_plugin_pb_kms_plugin_proto_rawDescOnce sync.Once
	file_plugin_pb_kms_plugin_proto_rawDescData []byte
)

func file_plugin_pb_kms_plugin_proto_rawDescGZIP() []byte {
	file_plugin_pb_kms_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_pb_kms_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_pb_kms_plugin_proto_rawDesc), len(file_plugin_pb_kms_plugin_proto_rawDesc)))
	})
	return file_plugin_pb_kms_plugin_proto_rawDescData
}

var file_plugin_pb_kms_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_plugin_pb_kms_plugin_proto_goTypes = []any{
	(*OpenRequest)(nil),          // 0: kms.OpenRequest
	(*OpenResponse)(nil),         // 1: kms.OpenResponse
	(*CloseRequest)(nil),         // 2: kms.CloseRequest
	(*CloseResponse)(nil),        // 3: kms.CloseResponse
	(*GetKeyRequest)(nil),        // 4: kms.GetKeyRequest
	(*GetKeyResponse)(nil),       // 5: kms.GetKeyResponse
	(*CloseKeyRequest)(nil),      // 6: kms.CloseKeyRequest
	(*CloseKeyResponse)(nil),     // 7: kms.CloseKeyResponse
	(*EncryptRequest)(nil),       // 8: kms.EncryptRequest
	(*EncryptResponse)(nil),      // 9: kms.EncryptResponse
	(*DecryptRequest)(nil),       // 10: kms.DecryptRequest
	(*DecryptResponse)(nil),      // 11: kms.DecryptResponse
	(*SignRequest)(nil),          // 12: kms.SignRequest
	(*SignResponse)(nil),         // 13: kms.SignResponse
	(*VerifyRequest)(nil),        // 14: kms.VerifyRequest
	(*VerifyResponse)(nil),       // 15: kms.VerifyResponse
	(*ExportPublicRequest)(nil),  // 16: kms.ExportPublicRequest
	(*ExportPublicResponse)(nil), // 17: kms.ExportPublicResponse
	(*SignerOpts)(nil),           // 18: kms.SignerOpts
	(*SignerOptsPSS)(nil),        // 19: kms.SignerOptsPSS
	(*SignerOptsEd25519)(nil),    // 20: kms.SignerOptsEd25519
	(*structpb.Struct)(nil),      // 21: google.protobuf.Struct
}
var file_plugin_pb_kms_plugin_proto_depIdxs = []int32{
	21, // 0: kms.OpenRequest.config_map:type_name -> google.protobuf.Struct
	21, // 1: kms.GetKeyRequest.config_map:type_name -> google.protobuf.Struct
	18, // 2: kms.SignRequest.opts:type_name -> kms.SignerOpts
	18, // 3: kms.VerifyRequest.opts:type_name -> kms.SignerOpts
	19, // 4: kms.SignerOpts.pss:type_name -> kms.SignerOptsPSS
	20, // 5: kms.SignerOpts.ed25519:type_name -> kms.SignerOptsEd25519
	0,  // 6: kms.KMS.Open:input_type -> kms.OpenRequest
	2,  // 7: kms.KMS.Close:input_type -> kms.CloseRequest
	4,  // 8: kms.KMS.GetKey:input_type -> kms.GetKeyRequest
	6,  // 9: kms.KMS.CloseKey:input_type -> kms.CloseKeyRequest
	8,  // 10: kms.KMS.Encrypt:input_type -> kms.EncryptRequest
	10, // 11: kms.KMS.Decrypt:input_type -> kms.DecryptRequest
	12, // 12: kms.KMS.Sign:input_type -> kms.SignRequest
	14, // 13: kms.KMS.Verify:input_type -> kms.VerifyRequest
	16, // 14: kms.KMS.ExportPublic:input_type -> kms.ExportPublicRequest
	1,  // 15: kms.KMS.Open:output_type -> kms.OpenResponse
	3,  // 16: kms.KMS.Close:output_type -> kms.CloseResponse
	5,  // 17: kms.KMS.GetKey:output_type -> kms.GetKeyResponse
	7,  // 18: kms.KMS.CloseKey:output_type -> kms.CloseKeyResponse
	9,  // 19: kms.KMS.Encrypt:output_type -> kms.EncryptResponse
	11, // 20: kms.KMS.Decrypt:output_type -> kms.DecryptResponse
	13, // 21: kms.KMS.Sign:output_type -> kms.SignResponse
	15, // 22: kms.KMS.Verify:output_type -> kms.VerifyResponse
	17, // 23: kms.KMS.ExportPublic:output_type -> kms.ExportPublicResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_pb_kms_plugin_proto_init() }
func file_plugin_pb_kms_plugin_proto_init() {
	if File_plugin_pb_kms_plugin_proto != nil {
		return
	}
	file_plugin_pb_kms_plugin_proto_msgTypes[12].OneofWrappers = []any{}
	file_plugin_pb_kms_plugin_proto_msgTypes[14].OneofWrappers = []any{}
	file_plugin_pb_kms_plugin_proto_msgTypes[18].OneofWrappers = []any{
		(*SignerOpts_Pss)(nil),
		(*SignerOpts_Ed25519)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pb_kms_plugin_proto_rawDesc), len(file_plugin_pb_kms_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_pb_kms_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_pb_kms_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_pb_kms_plugin_proto_msgTypes,
	}.Build()
	File_plugin_pb_kms_plugin_proto = out.File
	file_plugin_pb_kms_plugin_proto_goTypes = nil
	file_plugin_pb_kms_plugin_proto_depIdxs = nil
}
