// Copyright (c) 2026 OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

syntax = "proto3";

package kms;
option go_package = "github.com/openbao/go-kms-wrapping/plugin/v2/pb/kms;pb";

import "google/protobuf/struct.proto";

// See kms.Open and kms.OpenOptions.
message OpenRequest {
  bool allow_environment = 1;
  google.protobuf.Struct config_map = 10;
}
message OpenResponse {
  string kms_id = 1;
}

message CloseRequest {
  string kms_id = 1;
}
message CloseResponse {}

// See kms.KMS.GetKey and kms.KeyOptions.
message GetKeyRequest {
  string kms_id = 1;
  google.protobuf.Struct config_map = 10;
}
message GetKeyResponse {
  string key_id = 1;
}

message CloseKeyRequest {
  string key_id = 1;
}
message CloseKeyResponse {}

// See kms.Key.Encrypt and kms.CipherOptions.
message EncryptRequest {
  string key_id = 1;

  bytes data = 10;
  bytes aad = 11;
}
message EncryptResponse {
  bytes ciphertext = 1;
  bytes nonce = 2;
}

// See kms.Key.Decrypt and kms.CipherOptions.
message DecryptRequest {
  string key_id = 1;

  bytes data = 10;
  bytes aad = 11;
  bytes nonce = 12;
}
message DecryptResponse {
  bytes plaintext = 1;
}

// See kms.Key.Sign and kms.SignOptions.
message SignRequest {
  string key_id = 1;

  bytes data = 10;
  bool prehashed = 11;
  int32 hash = 12; // The value of HashFunc().
  optional SignerOpts opts = 13;
}
message SignResponse {
  bytes signature = 1;
}

// See kms.Key.Verify and kms.VerifyOptions.
message VerifyRequest {
  string key_id = 1;

  bytes data = 10;
  bool prehashed = 11;
  int32 hash = 12; // The value of HashFunc().
  optional SignerOpts opts = 13;

  bytes signature = 14;
}
message VerifyResponse {}

message ExportPublicRequest {
  string key_id = 1;
}
message ExportPublicResponse {
  // This might need to support different encodings in the future - for now,
  // all of *rsa.PublicKey, *ecdsa.PublicKey and ed25519.PublicKey are easily
  // transferred in PKIX ASN.1 DER encoding via x509.MarshalPKIXPublicKey and
  // x509.ParsePKIXPublicKey.
  //
  // Once additional encodings are needed, use the `oneof` keyword to expose
  // those as separate fields.
  bytes pkix_asn1_der = 1;
}

// This represents the well-known subset of crypto.SignerOpts. Note that
// HashFunc() is already embedded in SignRequest/VerifyRequest, this way the
// SignerOpts fields themselves can be `optional`.
message SignerOpts {
  oneof type {
    SignerOptsPSS pss = 1;
    SignerOptsEd25519 ed25519 = 2;
    // crypto/ecdsa defines no options.
  }
}

// See crypto/rsa.PSSOptions.
message SignerOptsPSS {
  int32 salt_length = 1;
}

// See crypto/ed25519.Options.
message SignerOptsEd25519 {
  string context = 1;
}

// See kms.KMS and kms.Key.
service KMS {
  rpc Open(OpenRequest) returns (OpenResponse);
  rpc Close(CloseRequest) returns (CloseResponse);

  rpc GetKey(GetKeyRequest) returns (GetKeyResponse);
  rpc CloseKey(CloseKeyRequest) returns (CloseKeyResponse);

  rpc Encrypt(EncryptRequest) returns (EncryptResponse);
  rpc Decrypt(DecryptRequest) returns (DecryptResponse);

  rpc Sign(SignRequest) returns (SignResponse);
  rpc Verify(VerifyRequest) returns (VerifyResponse);

  rpc ExportPublic(ExportPublicRequest) returns (ExportPublicResponse);
}
