// Copyright (c) 2026 OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: plugin/pb/metadata/plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_pb_metadata_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_metadata_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_pb_metadata_plugin_proto_rawDescGZIP(), []int{0}
}

// See plugin.Metadata struct.
type MetadataResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SensitiveKmsFields []string               `protobuf:"bytes,1,rep,name=sensitive_kms_fields,json=sensitiveKmsFields,proto3" json:"sensitive_kms_fields,omitempty"`
	SensitiveKeyFields []string               `protobuf:"bytes,2,rep,name=sensitive_key_fields,json=sensitiveKeyFields,proto3" json:"sensitive_key_fields,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_plugin_pb_metadata_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_metadata_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_plugin_pb_metadata_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetSensitiveKmsFields() []string {
	if x != nil {
		return x.SensitiveKmsFields
	}
	return nil
}

func (x *MetadataResponse) GetSensitiveKeyFields() []string {
	if x != nil {
		return x.SensitiveKeyFields
	}
	return nil
}

var File_plugin_pb_metadata_plugin_proto protoreflect.FileDescriptor

const file_plugin_pb_metadata_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1fplugin/pb/metadata/plugin.proto\x12\bmetadata\"\a\n" +
	"\x05Empty\"v\n" +
	"\x10MetadataResponse\x120\n" +
	"\x14sensitive_kms_fields\x18\x01 \x03(\tR\x12sensitiveKmsFields\x120\n" +
	"\x14sensitive_key_fields\x18\x02 \x03(\tR\x12sensitiveKeyFields2>\n" +
	"\bMetadata\x122\n" +
	"\x03Get\x12\x0f.metadata.Empty\x1a\x1a.metadata.MetadataResponseB=Z;github.com/openbao/go-kms-wrapping/plugin/v2/pb/metadata;pbb\x06proto3"

var (
	file_plugin_pb_metadata_plugin_proto_rawDescOnce sync.Once
	file_plugin_pb_metadata_plugin_proto_rawDescData []byte
)

func file_plugin_pb_metadata_plugin_proto_rawDescGZIP() []byte {
	file_plugin_pb_metadata_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_pb_metadata_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_pb_metadata_plugin_proto_rawDesc), len(file_plugin_pb_metadata_plugin_proto_rawDesc)))
	})
	return file_plugin_pb_metadata_plugin_proto_rawDescData
}

var file_plugin_pb_metadata_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_pb_metadata_plugin_proto_goTypes = []any{
	(*Empty)(nil),            // 0: metadata.Empty
	(*MetadataResponse)(nil), // 1: metadata.MetadataResponse
}
var file_plugin_pb_metadata_plugin_proto_depIdxs = []int32{
	0, // 0: metadata.Metadata.Get:input_type -> metadata.Empty
	1, // 1: metadata.Metadata.Get:output_type -> metadata.MetadataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_pb_metadata_plugin_proto_init() }
func file_plugin_pb_metadata_plugin_proto_init() {
	if File_plugin_pb_metadata_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pb_metadata_plugin_proto_rawDesc), len(file_plugin_pb_metadata_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_pb_metadata_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_pb_metadata_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_pb_metadata_plugin_proto_msgTypes,
	}.Build()
	File_plugin_pb_metadata_plugin_proto = out.File
	file_plugin_pb_metadata_plugin_proto_goTypes = nil
	file_plugin_pb_metadata_plugin_proto_depIdxs = nil
}
