// Copyright (c) 2025 Securosys SA.
package securosyshsm

import (
	"encoding/json"

	log "github.com/hashicorp/go-hclog"
	"github.com/mitchellh/cli"
)

// Struct storing generated data
type Key struct {
	// Key label from Securosys TSB
	RSALabel      string        `mapstructure:"rsa_label"`
	RSAPublicKey  string        `mapstructure:"rsa_public_key"`
	KeyAttributes KeyAttributes `mapstructure:"key_attributes"`
	RSAPassword   string        `mapstructure:"rsa_password"`
}

// Struct contains settings options
type Settings struct {
	// Authorization has been on of this consts [NONE,TOKEN,CERT]
	Auth string `mapstructure:"auth"`
	// BearerToken needed is needed only with Auth=TOKEN
	BearerToken string `mapstructure:"bearer_token"`
	// BasicToken needed is needed only with Auth=BASIC or if not exists You Have to prive UserName and Password
	// CertPath needed is needed only with Auth=CERT
	CertPath string `mapstructure:"cert_path"`
	// KeyPath needed is needed only with Auth=CERT
	KeyPath string `mapstructure:"key_path"`
	// Rest Api url where is located Securosys HSM
	RestApi string `mapstructure:"rest_api"`
	// Integer as Number in seconds for checking approval interval
	CheckEvery int `mapstructure:"check_every"`
	// ApprovalTimeout must be bigger then CheckEvery and lower then VAULT_CLIENT_TIMEOUT. Default: 60s
	ApprovalTimeout int `mapstructure:"approval_timeout"`
	// Enables/Disables debug on Securosys Requests. If not exists in config, then debug logs will be only awaylable in Tests
	Debug                  *bool            `mapstructure:"debug"`
	ApiKeys                ApiKeyTypes      `mapstructure:"api_keys"`
	ApplicationKeyPair     KeyPair          `mapstructure:"application_key_pair"`
	CurrentApiKeyTypeIndex ApiKeyTypesRetry `mapstructure:"current_api_key_type_index"`
}

// Main struct of securosys_hsm YML
type Configurations struct {
	// Struct With Application Settings
	Settings Settings `mapstructure:"settings"`
	// Autogenerated data from application. Do not change this manually!
	Key Key `mapstructure:"generated"`
}

type Logging struct {
	UI     cli.Ui
	Logger log.Logger
}

// Structure for all asychnronous operations
type RequestResponse struct {
	Id               string   `json:"id"`
	Status           string   `json:"status"`
	ExecutionTime    string   `json:"executionTime"`
	ApprovedBy       []string `json:"approvedBy"`
	NotYetApprovedBy []string `json:"notYetApprovedBy"`
	RejectedBy       []string `json:"rejectedBy"`
	Result           string   `json:"result"`
}

// Structure for get key attributes response
type KeyAttributes struct {
	Label              string          `mapstructure:"label"`
	Attributes         map[string]bool `mapstructure:"attributes"`
	KeySize            float64         `mapstructure:"key_size"`
	Policy             json.RawMessage `mapstructure:"policy"`
	PublicKey          string          `mapstructure:"public_key"`
	Algorithm          string          `mapstructure:"algorithm"`
	AlgorithmOid       string          `mapstructure:"algorithm_oid"`
	CurveOid           string          `mapstructure:"curve_oid"`
	Version            string          `mapstructure:"version"`
	Active             bool            `mapstructure:"active"`
	Xml                string          `mapstructure:"xml"`
	XmlSignature       string          `mapstructure:"xml_signature"`
	AttestationKeyName string          `mapstructure:"attestation_key_name"`
}

type KeyPair struct {
	PrivateKey *string `json:"privateKey,omitempty" mapstructure:"private_key"`
	PublicKey  *string `json:"publicKey,omitempty" mapstructure:"public_key"`
}

type ApiKeyTypes struct {
	KeyManagementToken         []string `json:"KeyManagementToken,omitempty" mapstructure:"key_management_token"`
	KeyOperationToken          []string `json:"KeyOperationToken,omitempty" mapstructure:"key_operation_token"`
	ApproverToken              []string `json:"ApproverToken,omitempty" mapstructure:"approver_token"`
	ServiceToken               []string `json:"ServiceToken,omitempty" mapstructure:"service_token"`
	ApproverKeyManagementToken []string `json:"ApproverKeyManagementToken,omitempty" mapstructure:"approver_key_management_token"`
}

func (keyTypes *ApiKeyTypes) ToJSON() string {
	marshal, err := json.Marshal(keyTypes)
	if err != nil {
		return ""
	}
	return string(marshal)
}

type ApiKeyTypesRetry struct {
	KeyManagementTokenIndex         int `mapstructure:"key_management_token_index"`
	KeyOperationTokenIndex          int `mapstructure:"key_operation_token_index"`
	ApproverTokenIndex              int `mapstructure:"approver_token_index"`
	ServiceTokenIndex               int `mapstructure:"service_token_index"`
	ApproverKeyManagementTokenIndex int `mapstructure:"approver_key_management_token_index"`
}

const (
	KeyManagementTokenName         = "KeyManagementToken"
	KeyOperationTokenName          = "KeyOperationToken"
	ApproverTokenName              = "ApproverToken"
	ServiceTokenName               = "ServiceToken"
	ApproverKeyManagementTokenName = "ApproverKeyManagementToken"
)
