name: Go

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        directory:
          - '.'
          - './plugin'
          - './wrappers/aead'
          - './wrappers/alicloudkms'
          - './wrappers/awskms'
          - './wrappers/azurekeyvault'
          - './wrappers/gcpckms'
          - './wrappers/huaweicloudkms'
          - './wrappers/kmip'
          - './wrappers/ocikms'
          - './wrappers/ovhcloudkms'
          - './wrappers/pkcs11'
          - './wrappers/static'
          - './wrappers/tcloudpublickms'
          - './wrappers/tencentcloudkms'
          - './wrappers/transit'
          - './kms/pkcs11'
          - './kms/transit'
        go:
          - '1.26'
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check for Dockerfile
        id: dockerfile
        working-directory: ${{ matrix.directory }}
        run: |-
          if [[ -f Dockerfile ]]; then
            echo exists=true >> $GITHUB_OUTPUT
          else
            echo exists=false >> $GITHUB_OUTPUT
          fi

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        if: steps.dockerfile.outputs.exists == 'false'
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: ${{ matrix.directory }}/go.mod

      - name: Tests
        if: steps.dockerfile.outputs.exists == 'false'
        working-directory: ${{ matrix.directory }}
        run: go test ./...

      - name: Container tests
        if: steps.dockerfile.outputs.exists == 'true'
        run: docker build -f '${{ matrix.directory }}/Dockerfile' .
